# Macro to download data files for the exercises.
macro(GetMasterclassResource filename)
  if(NOT EXISTS ${CMAKE_BINARY_DIR}/share/${CMAKE_PROJECT_NAME}/${filename})
    set(data_url http://lhcbproject.web.cern.ch/lhcbproject/dist/Masterclass/${filename})
    set(data_dest ${CMAKE_BINARY_DIR}/share/${CMAKE_PROJECT_NAME}/${filename})
    message(STATUS "Downloading data from ${data_url}")
    file(DOWNLOAD ${data_url} ${data_dest} STATUS dwld_status)
    list(GET dwld_status 0 status)
    if(status)
      list(GET dwld_status 1 mgs)
      message(WARNING "Failed to download data:\n${msg}\nYou have to download ${data_url} in ${data_dest} to use the program.")
    endif()
  endif()
endmacro()
