//
// File generated by C:\root\bin\rootcint.exe at Fri Jan 31 17:08:12 2014

// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "Dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void TVSDReader_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void delete_TVSDReader(void *p);
   static void deleteArray_TVSDReader(void *p);
   static void destruct_TVSDReader(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::TVSDReader*)
   {
      ::TVSDReader *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TVSDReader >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TVSDReader", ::TVSDReader::Class_Version(), "LHCb_D0_Exercise.h", 117,
                  typeid(::TVSDReader), DefineBehavior(ptr, ptr),
                  &::TVSDReader::Dictionary, isa_proxy, 0,
                  sizeof(::TVSDReader) );
      instance.SetDelete(&delete_TVSDReader);
      instance.SetDeleteArray(&deleteArray_TVSDReader);
      instance.SetDestructor(&destruct_TVSDReader);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::TVSDReader*)
   {
      return GenerateInitInstanceLocal((::TVSDReader*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TVSDReader*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *TVSDReader::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *TVSDReader::Class_Name()
{
   return "TVSDReader";
}

//______________________________________________________________________________
const char *TVSDReader::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TVSDReader*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TVSDReader::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TVSDReader*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TVSDReader::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TVSDReader*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TVSDReader::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TVSDReader*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void TVSDReader::Streamer(TBuffer &R__b)
{
   // Stream an object of class TVSDReader.

   TObject::Streamer(R__b);
}

//______________________________________________________________________________
void TVSDReader::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class TVSDReader.
      typedef ::TVSDReader msvc_bug_workaround;
      TClass *R__cl = msvc_bug_workaround::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "*d0File", &d0File);
      R__insp.Inspect(R__cl, R__parent, "*d0Tree", &d0Tree);
      R__insp.Inspect(R__cl, R__parent, "D0_MM", &D0_MM);
      R__insp.Inspect(R__cl, R__parent, "D0_PT", &D0_PT);
      R__insp.Inspect(R__cl, R__parent, "D0_TAU", &D0_TAU);
      R__insp.Inspect(R__cl, R__parent, "D0_MINIP", &D0_MINIP);
      R__insp.Inspect(R__cl, R__parent, "fittedMass", &fittedMass);
      R__insp.Inspect(R__cl, R__parent, "fittedTime", &fittedTime);
      R__insp.Inspect(R__cl, R__parent, "lang1", &lang1);
      R__insp.Inspect(R__cl, R__parent, "*fFile", &fFile);
      R__insp.Inspect(R__cl, R__parent, "*fDirectory", &fDirectory);
      R__insp.Inspect(R__cl, R__parent, "*fEvDirKeys", &fEvDirKeys);
      R__insp.Inspect(R__cl, R__parent, "*fVSD", &fVSD);
      R__insp.Inspect(R__cl, R__parent, "fMaxEv", &fMaxEv);
      R__insp.Inspect(R__cl, R__parent, "fCurEv", &fCurEv);
      R__insp.Inspect(R__cl, R__parent, "fMaxR", &fMaxR);
      R__insp.Inspect(R__cl, R__parent, "fRAnim", &fRAnim);
      R__insp.Inspect(R__cl, R__parent, "fAnalysis1", &fAnalysis1);
      R__insp.Inspect(R__cl, R__parent, "fAnalysis2", &fAnalysis2);
      R__insp.Inspect(R__cl, R__parent, "fVertexLoaded", &fVertexLoaded);
      R__insp.Inspect(R__cl, R__parent, "fITSClustersLoaded", &fITSClustersLoaded);
      R__insp.Inspect(R__cl, R__parent, "fTPCClustersLoaded", &fTPCClustersLoaded);
      R__insp.Inspect(R__cl, R__parent, "fTRDClustersLoaded", &fTRDClustersLoaded);
      R__insp.Inspect(R__cl, R__parent, "fTOFClustersLoaded", &fTOFClustersLoaded);
      R__insp.Inspect(R__cl, R__parent, "fClustersLoaded", &fClustersLoaded);
      R__insp.Inspect(R__cl, R__parent, "fEsdTracksLoaded", &fEsdTracksLoaded);
      R__insp.Inspect(R__cl, R__parent, "fV0sLoaded", &fV0sLoaded);
      R__insp.Inspect(R__cl, R__parent, "fCascadesLoaded", &fCascadesLoaded);
      R__insp.Inspect(R__cl, R__parent, "fGuidesLoaded", &fGuidesLoaded);
      R__insp.Inspect(R__cl, R__parent, "fGeometrySet", &fGeometrySet);
      R__insp.Inspect(R__cl, R__parent, "fInDemoMode", &fInDemoMode);
      R__insp.Inspect(R__cl, R__parent, "*fTrackList", &fTrackList);
      R__insp.Inspect(R__cl, R__parent, "*fTrackListV0Neg", &fTrackListV0Neg);
      R__insp.Inspect(R__cl, R__parent, "*fTrackListV0Pos", &fTrackListV0Pos);
      R__insp.Inspect(R__cl, R__parent, "*fTrackListV0Mother", &fTrackListV0Mother);
      R__insp.Inspect(R__cl, R__parent, "*fTrackListCascade", &fTrackListCascade);
      R__insp.Inspect(R__cl, R__parent, "*fTrackListCascadeNeg", &fTrackListCascadeNeg);
      R__insp.Inspect(R__cl, R__parent, "*fTrackListCascadePos", &fTrackListCascadePos);
      R__insp.Inspect(R__cl, R__parent, "*fTrackListCascadeBachelor", &fTrackListCascadeBachelor);
      R__insp.Inspect(R__cl, R__parent, "*fTrackListCascadeMother", &fTrackListCascadeMother);
      R__insp.Inspect(R__cl, R__parent, "*fTrackListPointingV0", &fTrackListPointingV0);
      R__insp.Inspect(R__cl, R__parent, "*fPsVertex", &fPsVertex);
      R__insp.Inspect(R__cl, R__parent, "*fITSClusters", &fITSClusters);
      R__insp.Inspect(R__cl, R__parent, "*fTPCClusters", &fTPCClusters);
      R__insp.Inspect(R__cl, R__parent, "*fTRDClusters", &fTRDClusters);
      R__insp.Inspect(R__cl, R__parent, "*fTOFClusters", &fTOFClusters);
      R__insp.Inspect(R__cl, R__parent, "*fPsV0", &fPsV0);
      R__insp.Inspect(R__cl, R__parent, "*fPsCascade", &fPsCascade);
      R__insp.Inspect(R__cl, R__parent, "*fTimer", &fTimer);
      R__insp.Inspect(R__cl, R__parent, "*obutton1", &obutton1);
      R__insp.Inspect(R__cl, R__parent, "*obutton2", &obutton2);
      R__insp.Inspect(R__cl, R__parent, "*obutton3", &obutton3);
      R__insp.Inspect(R__cl, R__parent, "*overlayButton", &overlayButton);
      R__insp.Inspect(R__cl, R__parent, "*fAnalysis1TE", &fAnalysis1TE);
      R__insp.Inspect(R__cl, R__parent, "*fAnalysis2TE", &fAnalysis2TE);
      R__insp.Inspect(R__cl, R__parent, "*fMinvHisto", &fMinvHisto);
      R__insp.Inspect(R__cl, R__parent, "*fD0PTHisto_Sig", &fD0PTHisto_Sig);
      R__insp.Inspect(R__cl, R__parent, "*fD0TAUHisto_Sig", &fD0TAUHisto_Sig);
      R__insp.Inspect(R__cl, R__parent, "*fD0IPHisto_Sig", &fD0IPHisto_Sig);
      R__insp.Inspect(R__cl, R__parent, "*fD0PTHisto_Bkg", &fD0PTHisto_Bkg);
      R__insp.Inspect(R__cl, R__parent, "*fD0TAUHisto_Bkg", &fD0TAUHisto_Bkg);
      R__insp.Inspect(R__cl, R__parent, "*fD0IPHisto_Bkg", &fD0IPHisto_Bkg);
      R__insp.Inspect(R__cl, R__parent, "fD0FitResultTrendPlot", (void*)&fD0FitResultTrendPlot);
      ::ROOT::GenericShowMembers("map<int,TGraphErrors*>", (void*)&fD0FitResultTrendPlot, R__insp, strcat(R__parent,"fD0FitResultTrendPlot."),false);
      R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "fTrendPadMap", (void*)&fTrendPadMap);
      ::ROOT::GenericShowMembers("map<int,UInt_t>", (void*)&fTrendPadMap, R__insp, strcat(R__parent,"fTrendPadMap."),false);
      R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "*fSigCacheForFit", &fSigCacheForFit);
      R__insp.Inspect(R__cl, R__parent, "*fBkgCacheForFit", &fBkgCacheForFit);
      R__insp.Inspect(R__cl, R__parent, "fD0Trend_FitResults", (void*)&fD0Trend_FitResults);
      ::ROOT::GenericShowMembers("map<int,std::vector<FitResults::FitPoint> >", (void*)&fD0Trend_FitResults, R__insp, strcat(R__parent,"fD0Trend_FitResults."),false);
      R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "*fPad", &fPad);
      R__insp.Inspect(R__cl, R__parent, "*fTrendPad", &fTrendPad);
      R__insp.Inspect(R__cl, R__parent, "*fFitPad", &fFitPad);
      R__insp.Inspect(R__cl, R__parent, "*fD0PTCut", &fD0PTCut);
      R__insp.Inspect(R__cl, R__parent, "*fD0TAUCut", &fD0TAUCut);
      R__insp.Inspect(R__cl, R__parent, "*fD0IPCut", &fD0IPCut);
      R__insp.Inspect(R__cl, R__parent, "*fFitRangeGaus", &fFitRangeGaus);
      R__insp.Inspect(R__cl, R__parent, "*fFitRangePoly", &fFitRangePoly);
      R__insp.Inspect(R__cl, R__parent, "*fResultButton1", &fResultButton1);
      R__insp.Inspect(R__cl, R__parent, "*fResultButton2", &fResultButton2);
      R__insp.Inspect(R__cl, R__parent, "*fResultButton3", &fResultButton3);
      R__insp.Inspect(R__cl, R__parent, "*fResultButton4", &fResultButton4);
      R__insp.Inspect(R__cl, R__parent, "*fResultButton5", &fResultButton5);
      R__insp.Inspect(R__cl, R__parent, "*fResultButton6", &fResultButton6);
      R__insp.Inspect(R__cl, R__parent, "*fResultButton7", &fResultButton7);
      R__insp.Inspect(R__cl, R__parent, "*fResultButton8", &fResultButton8);
      R__insp.Inspect(R__cl, R__parent, "fResultPicture1", &fResultPicture1);
      fResultPicture1.ShowMembers(R__insp, strcat(R__parent,"fResultPicture1.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "fResultPicture2", &fResultPicture2);
      fResultPicture2.ShowMembers(R__insp, strcat(R__parent,"fResultPicture2.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "fResultPicture3", &fResultPicture3);
      fResultPicture3.ShowMembers(R__insp, strcat(R__parent,"fResultPicture3.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "fResultPicture4", &fResultPicture4);
      fResultPicture4.ShowMembers(R__insp, strcat(R__parent,"fResultPicture4.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "fResultPicture5", &fResultPicture5);
      fResultPicture5.ShowMembers(R__insp, strcat(R__parent,"fResultPicture5.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "fResultPicture6", &fResultPicture6);
      fResultPicture6.ShowMembers(R__insp, strcat(R__parent,"fResultPicture6.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "fResultPicture7", &fResultPicture7);
      fResultPicture7.ShowMembers(R__insp, strcat(R__parent,"fResultPicture7.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "fResultPicture8", &fResultPicture8);
      fResultPicture8.ShowMembers(R__insp, strcat(R__parent,"fResultPicture8.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "*fFitGaus", &fFitGaus);
      R__insp.Inspect(R__cl, R__parent, "*fFitExpo", &fFitExpo);
      R__insp.Inspect(R__cl, R__parent, "*fFitPolynomial", &fFitPolynomial);
      R__insp.Inspect(R__cl, R__parent, "*fSaveDir", &fSaveDir);
      R__insp.Inspect(R__cl, R__parent, "*fLoadDir", &fLoadDir);
      R__insp.Inspect(R__cl, R__parent, "*fTeacherName", &fTeacherName);
      R__insp.Inspect(R__cl, R__parent, "*fFitCut", &fFitCut);
      R__insp.Inspect(R__cl, R__parent, "*fFitResult", &fFitResult);
      R__insp.Inspect(R__cl, R__parent, "*fFitErr", &fFitErr);
      R__insp.Inspect(R__cl, R__parent, "*fName1", &fName1);
      R__insp.Inspect(R__cl, R__parent, "filetosave", &filetosave);
      filetosave.ShowMembers(R__insp, strcat(R__parent,"filetosave.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "*fVarToTrend", &fVarToTrend);
      R__insp.Inspect(R__cl, R__parent, "*frmMain", &frmMain);
      R__insp.Inspect(R__cl, R__parent, "fPTRangeMin", &fPTRangeMin);
      R__insp.Inspect(R__cl, R__parent, "fPTRangeMax", &fPTRangeMax);
      R__insp.Inspect(R__cl, R__parent, "fTAURangeMin", &fTAURangeMin);
      R__insp.Inspect(R__cl, R__parent, "fTAURangeMax", &fTAURangeMax);
      R__insp.Inspect(R__cl, R__parent, "fIPRangeMin", &fIPRangeMin);
      R__insp.Inspect(R__cl, R__parent, "fIPRangeMax", &fIPRangeMax);
      R__insp.Inspect(R__cl, R__parent, "fTrendPadNum", &fTrendPadNum);
      R__insp.Inspect(R__cl, R__parent, "var_ranges", &var_ranges);
      var_ranges.ShowMembers(R__insp, strcat(R__parent,"var_ranges.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "an_tools", &an_tools);
      an_tools.ShowMembers(R__insp, strcat(R__parent,"an_tools.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "tools", &tools);
      tools.ShowMembers(R__insp, strcat(R__parent,"tools.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "bg_sub", &bg_sub);
      bg_sub.ShowMembers(R__insp, strcat(R__parent,"bg_sub.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "t_fit", &t_fit);
      t_fit.ShowMembers(R__insp, strcat(R__parent,"t_fit.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "save_res", &save_res);
      save_res.ShowMembers(R__insp, strcat(R__parent,"save_res.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "plt_mass", &plt_mass);
      plt_mass.ShowMembers(R__insp, strcat(R__parent,"plt_mass.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "plt_distr", &plt_distr);
      plt_distr.ShowMembers(R__insp, strcat(R__parent,"plt_distr.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "fit_sign", &fit_sign);
      fit_sign.ShowMembers(R__insp, strcat(R__parent,"fit_sign.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "f_name", &f_name);
      f_name.ShowMembers(R__insp, strcat(R__parent,"f_name.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "s_exit", &s_exit);
      s_exit.ShowMembers(R__insp, strcat(R__parent,"s_exit.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "reset_exe", &reset_exe);
      reset_exe.ShowMembers(R__insp, strcat(R__parent,"reset_exe.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "read_inst", &read_inst);
      read_inst.ShowMembers(R__insp, strcat(R__parent,"read_inst.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "sv_canv", &sv_canv);
      sv_canv.ShowMembers(R__insp, strcat(R__parent,"sv_canv.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "cl_trend", &cl_trend);
      cl_trend.ShowMembers(R__insp, strcat(R__parent,"cl_trend.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "pl_trend", &pl_trend);
      pl_trend.ShowMembers(R__insp, strcat(R__parent,"pl_trend.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "sv_res_fit", &sv_res_fit);
      sv_res_fit.ShowMembers(R__insp, strcat(R__parent,"sv_res_fit.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "fit_mass_dis", &fit_mass_dis);
      fit_mass_dis.ShowMembers(R__insp, strcat(R__parent,"fit_mass_dis.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "i1", &i1);
      i1.ShowMembers(R__insp, strcat(R__parent,"i1.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "i2", &i2);
      i2.ShowMembers(R__insp, strcat(R__parent,"i2.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "i3", &i3);
      i3.ShowMembers(R__insp, strcat(R__parent,"i3.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "i4", &i4);
      i4.ShowMembers(R__insp, strcat(R__parent,"i4.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "i5", &i5);
      i5.ShowMembers(R__insp, strcat(R__parent,"i5.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "i6", &i6);
      i6.ShowMembers(R__insp, strcat(R__parent,"i6.")); R__parent[R__ncp] = 0;
      TObject::ShowMembers(R__insp, R__parent);
}

namespace ROOT {
   // Wrapper around operator delete
   static void delete_TVSDReader(void *p) {
      delete ((::TVSDReader*)p);
   }
   static void deleteArray_TVSDReader(void *p) {
      delete [] ((::TVSDReader*)p);
   }
   static void destruct_TVSDReader(void *p) {
      typedef ::TVSDReader current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::TVSDReader

/********************************************************
* C:/Users/atrisovi/LHCbMasterclass/src/D0_Lifetime/Dict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

extern "C" void G__cpp_reset_tagtableDict();

extern "C" void G__set_cpp_environmentDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("LHCb_D0_Exercise.h");
  G__cpp_reset_tagtableDict();
}
#include <new>
extern "C" int G__cpp_dllrevDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* TVSDReader */
static int G__Dict_641_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TVSDReader* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new TVSDReader((const char*) G__int(libp->para[0]));
   } else {
     p = new((void*) gvp) TVSDReader((const char*) G__int(libp->para[0]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__DictLN_TVSDReader));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dict_641_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVSDReader*) G__getstructoffset())->ToStudent();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dict_641_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVSDReader*) G__getstructoffset())->Exit();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dict_641_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVSDReader*) G__getstructoffset())->SaveCanvas();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dict_641_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVSDReader*) G__getstructoffset())->SetFileName();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dict_641_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVSDReader*) G__getstructoffset())->Instructions();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dict_641_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVSDReader*) G__getstructoffset())->ResetExercise();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dict_641_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVSDReader*) G__getstructoffset())->LoadD0Ntuple((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dict_641_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVSDReader*) G__getstructoffset())->SetD0NtupleBranches();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dict_641_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVSDReader*) G__getstructoffset())->PlotFitResultsVsVar();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dict_641_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVSDReader*) G__getstructoffset())->SaveFitResult();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dict_641_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVSDReader*) G__getstructoffset())->PlotD0Mass();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dict_641_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVSDReader*) G__getstructoffset())->PlotVarDists();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dict_641_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVSDReader*) G__getstructoffset())->FitDecayTime();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dict_641_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVSDReader*) G__getstructoffset())->FitInvariantMass();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dict_641_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TVSDReader*) G__getstructoffset())->Background_Integral((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dict_641_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVSDReader*) G__getstructoffset())->AutomaticMenu();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dict_641_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVSDReader*) G__getstructoffset())->TrendPad();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dict_641_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVSDReader*) G__getstructoffset())->FitPad();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dict_641_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVSDReader*) G__getstructoffset())->VarPad();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dict_641_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVSDReader*) G__getstructoffset())->CloseWin();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dict_641_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVSDReader*) G__getstructoffset())->LHCbInfo();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dict_641_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVSDReader*) G__getstructoffset())->IT();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dict_641_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVSDReader*) G__getstructoffset())->RO();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dict_641_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVSDReader*) G__getstructoffset())->EN();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dict_641_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVSDReader*) G__getstructoffset())->FR();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dict_641_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVSDReader*) G__getstructoffset())->setLang1((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dict_641_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVSDReader*) G__getstructoffset())->DE();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dict_641_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((TVSDReader*) G__getstructoffset())->OpenTab((TList*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dict_641_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVSDReader*) G__getstructoffset())->ClearTrend();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dict_641_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((TVSDReader*) G__getstructoffset())->CheckTrend((const int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dict_641_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVSDReader*) G__getstructoffset())->DeleteHistograms();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dict_641_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TVSDReader::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dict_641_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TVSDReader::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dict_641_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) TVSDReader::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dict_641_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TVSDReader::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dict_641_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVSDReader*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dict_641_0_41(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TVSDReader::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dict_641_0_42(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TVSDReader::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dict_641_0_43(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TVSDReader::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dict_641_0_44(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TVSDReader::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__Dict_641_0_45(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   TVSDReader* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new TVSDReader(*(TVSDReader*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__DictLN_TVSDReader));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TVSDReader G__TTVSDReader;
static int G__Dict_641_0_46(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TVSDReader*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TVSDReader*) (soff+(sizeof(TVSDReader)*i)))->~G__TTVSDReader();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TVSDReader*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TVSDReader*) (soff))->~G__TTVSDReader();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* TVSDReader */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncDict {
 public:
  G__Sizep2memfuncDict(): p(&G__Sizep2memfuncDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncDict::*p)();
};

size_t G__get_sizep2memfuncDict()
{
  G__Sizep2memfuncDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__DictLN_TVSDReader))) {
     TVSDReader *G__Lderived;
     G__Lderived=(TVSDReader*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__DictLN_TVSDReader),G__get_linked_tagnum(&G__DictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableDict() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("Bool_t",103,-1,0,-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<TSchemaHelper>",117,G__get_linked_tagnum(&G__DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("_Ranit<ROOT::TSchemaHelper,difference_type,const_pointer,const_reference>",117,G__get_linked_tagnum(&G__DictLN__RanitlEROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,G__get_linked_tagnum(&G__DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::iterator_category,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::value_type,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::difference_type,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::pointer,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::reference>",117,G__get_linked_tagnum(&G__DictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__DictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,ROOT::TSchemaHelper,long>",117,G__get_linked_tagnum(&G__DictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,ROOT::TSchemaHelper,long,ROOT::TSchemaHelper*>",117,G__get_linked_tagnum(&G__DictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR),0,G__get_linked_tagnum(&G__DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::iterator_category,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::value_type,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::difference_type,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::pointer,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::reference>",117,G__get_linked_tagnum(&G__DictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,TGraphErrors*>",117,G__get_linked_tagnum(&G__DictLN_maplEintcOTGraphErrorsmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGraphErrorsmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,TGraphErrors*,less<int> >",117,G__get_linked_tagnum(&G__DictLN_maplEintcOTGraphErrorsmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGraphErrorsmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,UInt_t>",117,G__get_linked_tagnum(&G__DictLN_maplEintcOunsignedsPintcOlesslEintgRcOallocatorlEpairlEconstsPintcOunsignedsPintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,unsigned int>",117,G__get_linked_tagnum(&G__DictLN_maplEintcOunsignedsPintcOlesslEintgRcOallocatorlEpairlEconstsPintcOunsignedsPintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,unsigned int,less<int> >",117,G__get_linked_tagnum(&G__DictLN_maplEintcOunsignedsPintcOlesslEintgRcOallocatorlEpairlEconstsPintcOunsignedsPintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<FitResults::FitPoint>",117,G__get_linked_tagnum(&G__DictLN_vectorlEFitResultscLcLFitPointcOallocatorlEFitResultscLcLFitPointgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("_Ranit<FitResults::FitPoint,difference_type,const_pointer,const_reference>",117,G__get_linked_tagnum(&G__DictLN__RanitlEFitResultscLcLFitPointcOlongcOFitResultscLcLFitPointmUcOFitResultscLcLFitPointaNgR),0,G__get_linked_tagnum(&G__DictLN_vectorlEFitResultscLcLFitPointcOallocatorlEFitResultscLcLFitPointgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DictLN_reverse_iteratorlEvectorlEFitResultscLcLFitPointcOallocatorlEFitResultscLcLFitPointgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DictLN_vectorlEFitResultscLcLFitPointcOallocatorlEFitResultscLcLFitPointgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<FitResults::FitPoint,allocator<FitResults::FitPoint> >::iterator>::iterator_category,iterator_traits<vector<FitResults::FitPoint,allocator<FitResults::FitPoint> >::iterator>::value_type,iterator_traits<vector<FitResults::FitPoint,allocator<FitResults::FitPoint> >::iterator>::difference_type,iterator_traits<vector<FitResults::FitPoint,allocator<FitResults::FitPoint> >::iterator>::pointer,iterator_traits<vector<FitResults::FitPoint,allocator<FitResults::FitPoint> >::iterator>::reference>",117,G__get_linked_tagnum(&G__DictLN_iteratorlErandom_access_iterator_tagcOFitResultscLcLFitPointcOlongcOFitResultscLcLFitPointmUcOFitResultscLcLFitPointaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,FitResults::FitPoint>",117,G__get_linked_tagnum(&G__DictLN_iteratorlErandom_access_iterator_tagcOFitResultscLcLFitPointcOlongcOFitResultscLcLFitPointmUcOFitResultscLcLFitPointaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,FitResults::FitPoint,long>",117,G__get_linked_tagnum(&G__DictLN_iteratorlErandom_access_iterator_tagcOFitResultscLcLFitPointcOlongcOFitResultscLcLFitPointmUcOFitResultscLcLFitPointaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,FitResults::FitPoint,long,FitResults::FitPoint*>",117,G__get_linked_tagnum(&G__DictLN_iteratorlErandom_access_iterator_tagcOFitResultscLcLFitPointcOlongcOFitResultscLcLFitPointmUcOFitResultscLcLFitPointaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DictLN_reverse_iteratorlEvectorlEFitResultscLcLFitPointcOallocatorlEFitResultscLcLFitPointgRsPgRcLcLconst_iteratorgR),0,G__get_linked_tagnum(&G__DictLN_vectorlEFitResultscLcLFitPointcOallocatorlEFitResultscLcLFitPointgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<FitResults::FitPoint,allocator<FitResults::FitPoint> >::const_iterator>::iterator_category,iterator_traits<vector<FitResults::FitPoint,allocator<FitResults::FitPoint> >::const_iterator>::value_type,iterator_traits<vector<FitResults::FitPoint,allocator<FitResults::FitPoint> >::const_iterator>::difference_type,iterator_traits<vector<FitResults::FitPoint,allocator<FitResults::FitPoint> >::const_iterator>::pointer,iterator_traits<vector<FitResults::FitPoint,allocator<FitResults::FitPoint> >::const_iterator>::reference>",117,G__get_linked_tagnum(&G__DictLN_iteratorlErandom_access_iterator_tagcOFitResultscLcLFitPointcOlongcOFitResultscLcLFitPointmUcOFitResultscLcLFitPointaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,std::vector<FitResults::FitPoint> >",117,G__get_linked_tagnum(&G__DictLN_maplEintcOvectorlEFitResultscLcLFitPointcOallocatorlEFitResultscLcLFitPointgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEFitResultscLcLFitPointcOallocatorlEFitResultscLcLFitPointgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,vector<FitResults::FitPoint,allocator<FitResults::FitPoint> > >",117,G__get_linked_tagnum(&G__DictLN_maplEintcOvectorlEFitResultscLcLFitPointcOallocatorlEFitResultscLcLFitPointgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEFitResultscLcLFitPointcOallocatorlEFitResultscLcLFitPointgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,vector<FitResults::FitPoint,allocator<FitResults::FitPoint> >,less<int> >",117,G__get_linked_tagnum(&G__DictLN_maplEintcOvectorlEFitResultscLcLFitPointcOallocatorlEFitResultscLcLFitPointgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEFitResultscLcLFitPointcOallocatorlEFitResultscLcLFitPointgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* TVSDReader */
static void G__setup_memvarTVSDReader(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__DictLN_TVSDReader));
   { TVSDReader *p; p=(TVSDReader*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->d0File)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TFile),-1,-1,1,"d0File=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->d0Tree)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TTree),-1,-1,1,"d0Tree=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->D0_MM)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"D0_MM=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->D0_PT)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"D0_PT=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->D0_TAU)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"D0_TAU=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->D0_MINIP)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"D0_MINIP=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fittedMass)-(long)(p)),103,0,0,-1,-1,-1,1,"fittedMass=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fittedTime)-(long)(p)),103,0,0,-1,-1,-1,1,"fittedTime=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->lang1)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"lang1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fFile)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TFile),-1,-1,1,"fFile=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fDirectory)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TDirectory),-1,-1,1,"fDirectory=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fEvDirKeys)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TObjArray),-1,-1,1,"fEvDirKeys=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fVSD)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TEveVSD),-1,-1,1,"fVSD=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fMaxEv)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"fMaxEv=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fCurEv)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"fCurEv=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fMaxR)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"fMaxR=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fRAnim)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"fRAnim=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fAnalysis1)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"fAnalysis1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fAnalysis2)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"fAnalysis2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fVertexLoaded)-(long)(p)),103,0,0,-1,G__defined_typename("Bool_t"),-1,1,"fVertexLoaded=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fITSClustersLoaded)-(long)(p)),103,0,0,-1,G__defined_typename("Bool_t"),-1,1,"fITSClustersLoaded=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fTPCClustersLoaded)-(long)(p)),103,0,0,-1,G__defined_typename("Bool_t"),-1,1,"fTPCClustersLoaded=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fTRDClustersLoaded)-(long)(p)),103,0,0,-1,G__defined_typename("Bool_t"),-1,1,"fTRDClustersLoaded=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fTOFClustersLoaded)-(long)(p)),103,0,0,-1,G__defined_typename("Bool_t"),-1,1,"fTOFClustersLoaded=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fClustersLoaded)-(long)(p)),103,0,0,-1,G__defined_typename("Bool_t"),-1,1,"fClustersLoaded=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fEsdTracksLoaded)-(long)(p)),103,0,0,-1,G__defined_typename("Bool_t"),-1,1,"fEsdTracksLoaded=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fV0sLoaded)-(long)(p)),103,0,0,-1,G__defined_typename("Bool_t"),-1,1,"fV0sLoaded=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fCascadesLoaded)-(long)(p)),103,0,0,-1,G__defined_typename("Bool_t"),-1,1,"fCascadesLoaded=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fGuidesLoaded)-(long)(p)),103,0,0,-1,G__defined_typename("Bool_t"),-1,1,"fGuidesLoaded=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fGeometrySet)-(long)(p)),103,0,0,-1,G__defined_typename("Bool_t"),-1,1,"fGeometrySet=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fInDemoMode)-(long)(p)),103,0,0,-1,G__defined_typename("Bool_t"),-1,1,"fInDemoMode=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fTrackList)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TEveTrackList),-1,-1,1,"fTrackList=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fTrackListV0Neg)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TEveTrackList),-1,-1,1,"fTrackListV0Neg=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fTrackListV0Pos)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TEveTrackList),-1,-1,1,"fTrackListV0Pos=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fTrackListV0Mother)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TEveTrackList),-1,-1,1,"fTrackListV0Mother=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fTrackListCascade)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TEveTrackList),-1,-1,1,"fTrackListCascade=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fTrackListCascadeNeg)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TEveTrackList),-1,-1,1,"fTrackListCascadeNeg=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fTrackListCascadePos)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TEveTrackList),-1,-1,1,"fTrackListCascadePos=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fTrackListCascadeBachelor)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TEveTrackList),-1,-1,1,"fTrackListCascadeBachelor=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fTrackListCascadeMother)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TEveTrackList),-1,-1,1,"fTrackListCascadeMother=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fTrackListPointingV0)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TEveTrackList),-1,-1,1,"fTrackListPointingV0=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fPsVertex)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TEvePointSet),-1,-1,1,"fPsVertex=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fITSClusters)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TEvePointSet),-1,-1,1,"fITSClusters=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fTPCClusters)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TEvePointSet),-1,-1,1,"fTPCClusters=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fTRDClusters)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TEvePointSet),-1,-1,1,"fTRDClusters=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fTOFClusters)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TEvePointSet),-1,-1,1,"fTOFClusters=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fPsV0)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TEvePointSet),-1,-1,1,"fPsV0=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fPsCascade)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TEvePointSet),-1,-1,1,"fPsCascade=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fTimer)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TTimer),-1,-1,1,"fTimer=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->obutton1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TGLOverlayButton),-1,-1,1,"obutton1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->obutton2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TGLOverlayButton),-1,-1,1,"obutton2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->obutton3)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TGLOverlayButton),-1,-1,1,"obutton3=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->overlayButton)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TGLOverlayButton),-1,-1,1,"overlayButton=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fAnalysis1TE)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TGTextEntry),-1,-1,1,"fAnalysis1TE=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fAnalysis2TE)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TGTextEntry),-1,-1,1,"fAnalysis2TE=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fMinvHisto)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TH1D),-1,-1,1,"fMinvHisto=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fD0PTHisto_Sig)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TH1D),-1,-1,1,"fD0PTHisto_Sig=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fD0TAUHisto_Sig)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TH1D),-1,-1,1,"fD0TAUHisto_Sig=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fD0IPHisto_Sig)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TH1D),-1,-1,1,"fD0IPHisto_Sig=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fD0PTHisto_Bkg)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TH1D),-1,-1,1,"fD0PTHisto_Bkg=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fD0TAUHisto_Bkg)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TH1D),-1,-1,1,"fD0TAUHisto_Bkg=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fD0IPHisto_Bkg)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TH1D),-1,-1,1,"fD0IPHisto_Bkg=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fD0FitResultTrendPlot)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__DictLN_maplEintcOTGraphErrorsmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGraphErrorsmUgRsPgRsPgR),G__defined_typename("map<int,TGraphErrors*>"),-1,1,"fD0FitResultTrendPlot=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fTrendPadMap)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__DictLN_maplEintcOunsignedsPintcOlesslEintgRcOallocatorlEpairlEconstsPintcOunsignedsPintgRsPgRsPgR),G__defined_typename("map<int,UInt_t>"),-1,1,"fTrendPadMap=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fSigCacheForFit)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TH1D),-1,-1,1,"fSigCacheForFit=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fBkgCacheForFit)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TH1D),-1,-1,1,"fBkgCacheForFit=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fD0Trend_FitResults)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__DictLN_maplEintcOvectorlEFitResultscLcLFitPointcOallocatorlEFitResultscLcLFitPointgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEFitResultscLcLFitPointcOallocatorlEFitResultscLcLFitPointgRsPgRsPgRsPgRsPgR),G__defined_typename("map<int,std::vector<FitResults::FitPoint> >"),-1,1,"fD0Trend_FitResults=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fPad)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TCanvas),-1,-1,1,"fPad=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fTrendPad)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TCanvas),-1,-1,1,"fTrendPad=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fFitPad)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TCanvas),-1,-1,1,"fFitPad=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fD0PTCut)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TEveGDoubleValuator),-1,-1,1,"fD0PTCut=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fD0TAUCut)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TEveGDoubleValuator),-1,-1,1,"fD0TAUCut=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fD0IPCut)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TEveGDoubleValuator),-1,-1,1,"fD0IPCut=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fFitRangeGaus)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TEveGDoubleValuator),-1,-1,1,"fFitRangeGaus=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fFitRangePoly)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TEveGDoubleValuator),-1,-1,1,"fFitRangePoly=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fResultButton1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TGPictureButton),-1,-1,1,"fResultButton1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fResultButton2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TGPictureButton),-1,-1,1,"fResultButton2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fResultButton3)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TGPictureButton),-1,-1,1,"fResultButton3=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fResultButton4)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TGPictureButton),-1,-1,1,"fResultButton4=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fResultButton5)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TGPictureButton),-1,-1,1,"fResultButton5=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fResultButton6)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TGPictureButton),-1,-1,1,"fResultButton6=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fResultButton7)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TGPictureButton),-1,-1,1,"fResultButton7=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fResultButton8)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TGPictureButton),-1,-1,1,"fResultButton8=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fResultPicture1)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__DictLN_TString),-1,-1,1,"fResultPicture1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fResultPicture2)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__DictLN_TString),-1,-1,1,"fResultPicture2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fResultPicture3)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__DictLN_TString),-1,-1,1,"fResultPicture3=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fResultPicture4)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__DictLN_TString),-1,-1,1,"fResultPicture4=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fResultPicture5)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__DictLN_TString),-1,-1,1,"fResultPicture5=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fResultPicture6)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__DictLN_TString),-1,-1,1,"fResultPicture6=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fResultPicture7)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__DictLN_TString),-1,-1,1,"fResultPicture7=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fResultPicture8)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__DictLN_TString),-1,-1,1,"fResultPicture8=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fFitGaus)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TF1),-1,-1,1,"fFitGaus=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fFitExpo)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TF1),-1,-1,1,"fFitExpo=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fFitPolynomial)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TF1),-1,-1,1,"fFitPolynomial=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fSaveDir)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TGComboBox),-1,-1,1,"fSaveDir=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fLoadDir)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TGComboBox),-1,-1,1,"fLoadDir=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fTeacherName)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TGTextEntry),-1,-1,1,"fTeacherName=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fFitCut)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TGNumberEntryField),-1,-1,1,"fFitCut=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fFitResult)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TGNumberEntryField),-1,-1,1,"fFitResult=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fFitErr)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TGNumberEntryField),-1,-1,1,"fFitErr=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fName1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TGTextEntry),-1,-1,1,"fName1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->filetosave)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__DictLN_TString),-1,-1,1,"filetosave=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fVarToTrend)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TGComboBox),-1,-1,1,"fVarToTrend=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->frmMain)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__DictLN_TGMainFrame),-1,-1,1,"frmMain=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,1,-1,-1,-1,4,"fPTRangeMin=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,1,-1,-1,-1,4,"fPTRangeMax=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,1,-1,-1,-1,4,"fTAURangeMin=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,1,-1,-1,-1,4,"fTAURangeMax=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,1,-1,-1,-1,4,"fIPRangeMin=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,1,-1,-1,-1,4,"fIPRangeMax=",0,(char*)NULL);
   G__memvar_setup((void*)0,104,0,0,-1,G__defined_typename("UInt_t"),-1,4,"fTrendPadNum=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DictLN_TString),-1,-1,4,"var_ranges=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DictLN_TString),-1,-1,4,"an_tools=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DictLN_TString),-1,-1,4,"tools=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DictLN_TString),-1,-1,4,"bg_sub=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DictLN_TString),-1,-1,4,"t_fit=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DictLN_TString),-1,-1,4,"save_res=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DictLN_TString),-1,-1,4,"plt_mass=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DictLN_TString),-1,-1,4,"plt_distr=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DictLN_TString),-1,-1,4,"fit_sign=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DictLN_TString),-1,-1,4,"f_name=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DictLN_TString),-1,-1,4,"s_exit=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DictLN_TString),-1,-1,4,"reset_exe=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DictLN_TString),-1,-1,4,"read_inst=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DictLN_TString),-1,-1,4,"sv_canv=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DictLN_TString),-1,-1,4,"cl_trend=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DictLN_TString),-1,-1,4,"pl_trend=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DictLN_TString),-1,-1,4,"sv_res_fit=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DictLN_TString),-1,-1,4,"fit_mass_dis=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DictLN_TString),-1,-1,4,"i1=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DictLN_TString),-1,-1,4,"i2=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DictLN_TString),-1,-1,4,"i3=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DictLN_TString),-1,-1,4,"i4=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DictLN_TString),-1,-1,4,"i5=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DictLN_TString),-1,-1,4,"i6=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTVSDReader(void) {
   /* TVSDReader */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__DictLN_TVSDReader));
   G__memfunc_setup("TVSDReader",916,G__Dict_641_0_1, 105, G__get_linked_tagnum(&G__DictLN_TVSDReader), -1, 0, 1, 1, 1, 0, "C - - 10 - file_name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ToStudent",938,G__Dict_641_0_2, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Exit",410,G__Dict_641_0_3, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SaveCanvas",1003,G__Dict_641_0_4, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetFileName",1069,G__Dict_641_0_5, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Instructions",1301,G__Dict_641_0_6, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ResetExercise",1339,G__Dict_641_0_7, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("LoadD0Ntuple",1132,G__Dict_641_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - file_name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetD0NtupleBranches",1854,G__Dict_641_0_9, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PlotFitResultsVsVar",1958,G__Dict_641_0_10, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SaveFitResult",1329,G__Dict_641_0_11, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PlotD0Mass",935,G__Dict_641_0_12, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PlotVarDists",1231,G__Dict_641_0_13, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FitDecayTime",1176,G__Dict_641_0_14, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FitInvariantMass",1635,G__Dict_641_0_15, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Background_Integral",1941,G__Dict_641_0_16, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 0, 
"d - 'Double_t' 0 - xmin d - 'Double_t' 0 - xmax", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AutomaticMenu",1340,G__Dict_641_0_17, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TrendPad",786,G__Dict_641_0_18, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FitPad",568,G__Dict_641_0_19, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("VarPad",574,G__Dict_641_0_20, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CloseWin",804,G__Dict_641_0_21, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("LHCbInfo",709,G__Dict_641_0_22, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("IT",157,G__Dict_641_0_23, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("RO",161,G__Dict_641_0_24, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("EN",147,G__Dict_641_0_25, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FR",152,G__Dict_641_0_26, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setLang1",767,G__Dict_641_0_27, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - lang", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DE",137,G__Dict_641_0_28, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("OpenTab",681,G__Dict_641_0_29, 103, -1, -1, 0, 2, 1, 1, 0, 
"U 'TList' - 0 - tabs C - - 10 - str", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ClearTrend",996,G__Dict_641_0_30, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CheckTrend",987,G__Dict_641_0_31, 103, -1, G__defined_typename("Bool_t"), 0, 1, 1, 1, 0, "i - - 10 - choice", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeleteHistograms",1652,G__Dict_641_0_32, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__Dict_641_0_33, 85, G__get_linked_tagnum(&G__DictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TVSDReader::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__Dict_641_0_34, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TVSDReader::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__Dict_641_0_35, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TVSDReader::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__Dict_641_0_36, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TVSDReader::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__DictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"u 'TMemberInspector' - 1 - insp C - - 0 - parent", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__Dict_641_0_40, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__Dict_641_0_41, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TVSDReader::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__Dict_641_0_42, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TVSDReader::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__Dict_641_0_43, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TVSDReader::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__Dict_641_0_44, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TVSDReader::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("TVSDReader", 916, G__Dict_641_0_45, (int) ('i'), G__get_linked_tagnum(&G__DictLN_TVSDReader), -1, 0, 1, 1, 1, 0, "u 'TVSDReader' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~TVSDReader", 1042, G__Dict_641_0_46, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__DictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__DictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__DictLN_TDirectory = { "TDirectory" , 99 , -1 };
G__linked_taginfo G__DictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__DictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__DictLN__RanitlEROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR = { "_Ranit<ROOT::TSchemaHelper,long,ROOT::TSchemaHelper*,ROOT::TSchemaHelper&>" , 115 , -1 };
G__linked_taginfo G__DictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR = { "iterator<random_access_iterator_tag,ROOT::TSchemaHelper,long,ROOT::TSchemaHelper*,ROOT::TSchemaHelper&>" , 115 , -1 };
G__linked_taginfo G__DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>" , 99 , -1 };
G__linked_taginfo G__DictLN_TList = { "TList" , 99 , -1 };
G__linked_taginfo G__DictLN_TObjArray = { "TObjArray" , 99 , -1 };
G__linked_taginfo G__DictLN_TTimer = { "TTimer" , 99 , -1 };
G__linked_taginfo G__DictLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__DictLN_TGMainFrame = { "TGMainFrame" , 99 , -1 };
G__linked_taginfo G__DictLN_TGTextEntry = { "TGTextEntry" , 99 , -1 };
G__linked_taginfo G__DictLN_TGPictureButton = { "TGPictureButton" , 99 , -1 };
G__linked_taginfo G__DictLN_TGComboBox = { "TGComboBox" , 99 , -1 };
G__linked_taginfo G__DictLN_TFile = { "TFile" , 99 , -1 };
G__linked_taginfo G__DictLN_TTree = { "TTree" , 99 , -1 };
G__linked_taginfo G__DictLN_TEveVSD = { "TEveVSD" , 99 , -1 };
G__linked_taginfo G__DictLN_TEveTrackList = { "TEveTrackList" , 99 , -1 };
G__linked_taginfo G__DictLN_TEvePointSet = { "TEvePointSet" , 99 , -1 };
G__linked_taginfo G__DictLN_TGLOverlayButton = { "TGLOverlayButton" , 99 , -1 };
G__linked_taginfo G__DictLN_TH1D = { "TH1D" , 99 , -1 };
G__linked_taginfo G__DictLN_TEveGDoubleValuator = { "TEveGDoubleValuator" , 99 , -1 };
G__linked_taginfo G__DictLN_TCanvas = { "TCanvas" , 99 , -1 };
G__linked_taginfo G__DictLN_TF1 = { "TF1" , 99 , -1 };
G__linked_taginfo G__DictLN_TGNumberEntryField = { "TGNumberEntryField" , 99 , -1 };
G__linked_taginfo G__DictLN_TVSDReader = { "TVSDReader" , 99 , -1 };
G__linked_taginfo G__DictLN_maplEintcOTGraphErrorsmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGraphErrorsmUgRsPgRsPgR = { "map<int,TGraphErrors*,less<int>,allocator<pair<const int,TGraphErrors*> > >" , 99 , -1 };
G__linked_taginfo G__DictLN_maplEintcOunsignedsPintcOlesslEintgRcOallocatorlEpairlEconstsPintcOunsignedsPintgRsPgRsPgR = { "map<int,unsigned int,less<int>,allocator<pair<const int,unsigned int> > >" , 99 , -1 };
G__linked_taginfo G__DictLN_vectorlEFitResultscLcLFitPointcOallocatorlEFitResultscLcLFitPointgRsPgR = { "vector<FitResults::FitPoint,allocator<FitResults::FitPoint> >" , 99 , -1 };
G__linked_taginfo G__DictLN__RanitlEFitResultscLcLFitPointcOlongcOFitResultscLcLFitPointmUcOFitResultscLcLFitPointaNgR = { "_Ranit<FitResults::FitPoint,long,FitResults::FitPoint*,FitResults::FitPoint&>" , 115 , -1 };
G__linked_taginfo G__DictLN_iteratorlErandom_access_iterator_tagcOFitResultscLcLFitPointcOlongcOFitResultscLcLFitPointmUcOFitResultscLcLFitPointaNgR = { "iterator<random_access_iterator_tag,FitResults::FitPoint,long,FitResults::FitPoint*,FitResults::FitPoint&>" , 115 , -1 };
G__linked_taginfo G__DictLN_reverse_iteratorlEvectorlEFitResultscLcLFitPointcOallocatorlEFitResultscLcLFitPointgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<FitResults::FitPoint,allocator<FitResults::FitPoint> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DictLN_reverse_iteratorlEvectorlEFitResultscLcLFitPointcOallocatorlEFitResultscLcLFitPointgRsPgRcLcLconst_iteratorgR = { "reverse_iterator<vector<FitResults::FitPoint,allocator<FitResults::FitPoint> >::const_iterator>" , 99 , -1 };
G__linked_taginfo G__DictLN_maplEintcOvectorlEFitResultscLcLFitPointcOallocatorlEFitResultscLcLFitPointgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEFitResultscLcLFitPointcOallocatorlEFitResultscLcLFitPointgRsPgRsPgRsPgRsPgR = { "map<int,vector<FitResults::FitPoint,allocator<FitResults::FitPoint> >,less<int>,allocator<pair<const int,vector<FitResults::FitPoint,allocator<FitResults::FitPoint> > > > >" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableDict() {
  G__DictLN_TClass.tagnum = -1 ;
  G__DictLN_TBuffer.tagnum = -1 ;
  G__DictLN_TDirectory.tagnum = -1 ;
  G__DictLN_TMemberInspector.tagnum = -1 ;
  G__DictLN_TObject.tagnum = -1 ;
  G__DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__DictLN__RanitlEROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR.tagnum = -1 ;
  G__DictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR.tagnum = -1 ;
  G__DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR.tagnum = -1 ;
  G__DictLN_TList.tagnum = -1 ;
  G__DictLN_TObjArray.tagnum = -1 ;
  G__DictLN_TTimer.tagnum = -1 ;
  G__DictLN_TString.tagnum = -1 ;
  G__DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__DictLN_TGMainFrame.tagnum = -1 ;
  G__DictLN_TGTextEntry.tagnum = -1 ;
  G__DictLN_TGPictureButton.tagnum = -1 ;
  G__DictLN_TGComboBox.tagnum = -1 ;
  G__DictLN_TFile.tagnum = -1 ;
  G__DictLN_TTree.tagnum = -1 ;
  G__DictLN_TEveVSD.tagnum = -1 ;
  G__DictLN_TEveTrackList.tagnum = -1 ;
  G__DictLN_TEvePointSet.tagnum = -1 ;
  G__DictLN_TGLOverlayButton.tagnum = -1 ;
  G__DictLN_TH1D.tagnum = -1 ;
  G__DictLN_TEveGDoubleValuator.tagnum = -1 ;
  G__DictLN_TCanvas.tagnum = -1 ;
  G__DictLN_TF1.tagnum = -1 ;
  G__DictLN_TGNumberEntryField.tagnum = -1 ;
  G__DictLN_TVSDReader.tagnum = -1 ;
  G__DictLN_maplEintcOTGraphErrorsmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGraphErrorsmUgRsPgRsPgR.tagnum = -1 ;
  G__DictLN_maplEintcOunsignedsPintcOlesslEintgRcOallocatorlEpairlEconstsPintcOunsignedsPintgRsPgRsPgR.tagnum = -1 ;
  G__DictLN_vectorlEFitResultscLcLFitPointcOallocatorlEFitResultscLcLFitPointgRsPgR.tagnum = -1 ;
  G__DictLN__RanitlEFitResultscLcLFitPointcOlongcOFitResultscLcLFitPointmUcOFitResultscLcLFitPointaNgR.tagnum = -1 ;
  G__DictLN_iteratorlErandom_access_iterator_tagcOFitResultscLcLFitPointcOlongcOFitResultscLcLFitPointmUcOFitResultscLcLFitPointaNgR.tagnum = -1 ;
  G__DictLN_reverse_iteratorlEvectorlEFitResultscLcLFitPointcOallocatorlEFitResultscLcLFitPointgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DictLN_reverse_iteratorlEvectorlEFitResultscLcLFitPointcOallocatorlEFitResultscLcLFitPointgRsPgRcLcLconst_iteratorgR.tagnum = -1 ;
  G__DictLN_maplEintcOvectorlEFitResultscLcLFitPointcOallocatorlEFitResultscLcLFitPointgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEFitResultscLcLFitPointcOallocatorlEFitResultscLcLFitPointgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__DictLN_TClass);
   G__get_linked_tagnum_fwd(&G__DictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__DictLN_TDirectory);
   G__get_linked_tagnum_fwd(&G__DictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__DictLN_TObject);
   G__get_linked_tagnum_fwd(&G__DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__DictLN__RanitlEROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR);
   G__get_linked_tagnum_fwd(&G__DictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR);
   G__get_linked_tagnum_fwd(&G__DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR);
   G__get_linked_tagnum_fwd(&G__DictLN_TList);
   G__get_linked_tagnum_fwd(&G__DictLN_TObjArray);
   G__get_linked_tagnum_fwd(&G__DictLN_TTimer);
   G__get_linked_tagnum_fwd(&G__DictLN_TString);
   G__get_linked_tagnum_fwd(&G__DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__DictLN_TGMainFrame);
   G__get_linked_tagnum_fwd(&G__DictLN_TGTextEntry);
   G__get_linked_tagnum_fwd(&G__DictLN_TGPictureButton);
   G__get_linked_tagnum_fwd(&G__DictLN_TGComboBox);
   G__get_linked_tagnum_fwd(&G__DictLN_TFile);
   G__get_linked_tagnum_fwd(&G__DictLN_TTree);
   G__get_linked_tagnum_fwd(&G__DictLN_TEveVSD);
   G__get_linked_tagnum_fwd(&G__DictLN_TEveTrackList);
   G__get_linked_tagnum_fwd(&G__DictLN_TEvePointSet);
   G__get_linked_tagnum_fwd(&G__DictLN_TGLOverlayButton);
   G__get_linked_tagnum_fwd(&G__DictLN_TH1D);
   G__get_linked_tagnum_fwd(&G__DictLN_TEveGDoubleValuator);
   G__get_linked_tagnum_fwd(&G__DictLN_TCanvas);
   G__get_linked_tagnum_fwd(&G__DictLN_TF1);
   G__get_linked_tagnum_fwd(&G__DictLN_TGNumberEntryField);
   G__tagtable_setup(G__get_linked_tagnum(&G__DictLN_TVSDReader),sizeof(TVSDReader),-1,62464,(char*)NULL,G__setup_memvarTVSDReader,G__setup_memfuncTVSDReader);
   G__get_linked_tagnum_fwd(&G__DictLN_maplEintcOTGraphErrorsmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGraphErrorsmUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__DictLN_maplEintcOunsignedsPintcOlesslEintgRcOallocatorlEpairlEconstsPintcOunsignedsPintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__DictLN_vectorlEFitResultscLcLFitPointcOallocatorlEFitResultscLcLFitPointgRsPgR);
   G__get_linked_tagnum_fwd(&G__DictLN__RanitlEFitResultscLcLFitPointcOlongcOFitResultscLcLFitPointmUcOFitResultscLcLFitPointaNgR);
   G__get_linked_tagnum_fwd(&G__DictLN_iteratorlErandom_access_iterator_tagcOFitResultscLcLFitPointcOlongcOFitResultscLcLFitPointmUcOFitResultscLcLFitPointaNgR);
   G__get_linked_tagnum_fwd(&G__DictLN_reverse_iteratorlEvectorlEFitResultscLcLFitPointcOallocatorlEFitResultscLcLFitPointgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DictLN_reverse_iteratorlEvectorlEFitResultscLcLFitPointcOallocatorlEFitResultscLcLFitPointgRsPgRcLcLconst_iteratorgR);
   G__get_linked_tagnum_fwd(&G__DictLN_maplEintcOvectorlEFitResultscLcLFitPointcOallocatorlEFitResultscLcLFitPointgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEFitResultscLcLFitPointcOallocatorlEFitResultscLcLFitPointgRsPgRsPgRsPgRsPgR);
}
extern "C" void G__cpp_setupDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupDict()");
  G__set_cpp_environmentDict();
  G__cpp_setup_tagtableDict();

  G__cpp_setup_inheritanceDict();

  G__cpp_setup_typetableDict();

  G__cpp_setup_memvarDict();

  G__cpp_setup_memfuncDict();
  G__cpp_setup_globalDict();
  G__cpp_setup_funcDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncDict();
  return;
}
class G__cpp_setup_initDict {
  public:
    G__cpp_setup_initDict() { G__add_setup_func("Dict",(G__incsetup)(&G__cpp_setupDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initDict() { G__remove_setup_func("Dict"); }
};
G__cpp_setup_initDict G__cpp_setup_initializerDict;

