/********************************************************************
* C:/Users/atrisovi/LHCbMasterclass/src/D0_Lifetime/Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error C:/Users/atrisovi/LHCbMasterclass/src/D0_Lifetime/Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern G__DLLEXPORT int G__cpp_dllrevDict();
extern G__DLLEXPORT void G__set_cpp_environmentDict();
extern G__DLLEXPORT void G__cpp_setup_tagtableDict();
extern G__DLLEXPORT void G__cpp_setup_inheritanceDict();
extern G__DLLEXPORT void G__cpp_setup_typetableDict();
extern G__DLLEXPORT void G__cpp_setup_memvarDict();
extern G__DLLEXPORT void G__cpp_setup_globalDict();
extern G__DLLEXPORT void G__cpp_setup_memfuncDict();
extern G__DLLEXPORT void G__cpp_setup_funcDict();
extern G__DLLEXPORT void G__cpp_setupDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "LHCb_D0_Exercise.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__DictLN_TClass;
extern G__linked_taginfo G__DictLN_TBuffer;
extern G__linked_taginfo G__DictLN_TDirectory;
extern G__linked_taginfo G__DictLN_TMemberInspector;
extern G__linked_taginfo G__DictLN_TObject;
extern G__linked_taginfo G__DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__DictLN__RanitlEROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR;
extern G__linked_taginfo G__DictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR;
extern G__linked_taginfo G__DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__DictLN_TList;
extern G__linked_taginfo G__DictLN_TObjArray;
extern G__linked_taginfo G__DictLN_TTimer;
extern G__linked_taginfo G__DictLN_TString;
extern G__linked_taginfo G__DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__DictLN_TGMainFrame;
extern G__linked_taginfo G__DictLN_TGTextEntry;
extern G__linked_taginfo G__DictLN_TGPictureButton;
extern G__linked_taginfo G__DictLN_TGComboBox;
extern G__linked_taginfo G__DictLN_TFile;
extern G__linked_taginfo G__DictLN_TTree;
extern G__linked_taginfo G__DictLN_TEveVSD;
extern G__linked_taginfo G__DictLN_TEveTrackList;
extern G__linked_taginfo G__DictLN_TEvePointSet;
extern G__linked_taginfo G__DictLN_TGLOverlayButton;
extern G__linked_taginfo G__DictLN_TH1D;
extern G__linked_taginfo G__DictLN_TEveGDoubleValuator;
extern G__linked_taginfo G__DictLN_TCanvas;
extern G__linked_taginfo G__DictLN_TF1;
extern G__linked_taginfo G__DictLN_TGNumberEntryField;
extern G__linked_taginfo G__DictLN_TVSDReader;
extern G__linked_taginfo G__DictLN_maplEintcOTGraphErrorsmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGraphErrorsmUgRsPgRsPgR;
extern G__linked_taginfo G__DictLN_maplEintcOunsignedsPintcOlesslEintgRcOallocatorlEpairlEconstsPintcOunsignedsPintgRsPgRsPgR;
extern G__linked_taginfo G__DictLN_vectorlEFitResultscLcLFitPointcOallocatorlEFitResultscLcLFitPointgRsPgR;
extern G__linked_taginfo G__DictLN__RanitlEFitResultscLcLFitPointcOlongcOFitResultscLcLFitPointmUcOFitResultscLcLFitPointaNgR;
extern G__linked_taginfo G__DictLN_iteratorlErandom_access_iterator_tagcOFitResultscLcLFitPointcOlongcOFitResultscLcLFitPointmUcOFitResultscLcLFitPointaNgR;
extern G__linked_taginfo G__DictLN_reverse_iteratorlEvectorlEFitResultscLcLFitPointcOallocatorlEFitResultscLcLFitPointgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictLN_reverse_iteratorlEvectorlEFitResultscLcLFitPointcOallocatorlEFitResultscLcLFitPointgRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__DictLN_maplEintcOvectorlEFitResultscLcLFitPointcOallocatorlEFitResultscLcLFitPointgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEFitResultscLcLFitPointcOallocatorlEFitResultscLcLFitPointgRsPgRsPgRsPgRsPgR;

/* STUB derived class for protected member access */
